title: "Chantel Bawuah"
author: "Chantel Bawuah"
description: "Data Science | Machine Learning | Analytics"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_social: true          # shows site description and social links in the footer 
show_excerpts: false       # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "CHANTEL BAWUAH.pdf", title: "CV"}
  - {title: "Projects", url: "https://github.com/Chan-Tel/Sentiment-Analysis/blob/4b30cb165ad3827bd81cd4c70f054587d878e34e/sentiment-analysis-on-tripadvisor-hotel-reviews.ipynb"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:chantelbawuah@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/Chan-Tel"}
  - {title: Linkedin, icon: linkedin, url: "https://www.linkedin.com/in/chantelbawuah"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
